#!/bin/sh
# env.sh -- compose .env from .env.template, local overrides, and .env.ports.
#
# NOT a cp, and not a cat. `cat template ports > .env` clobbers every local
# edit silently: change BUILD_SHA to debug something, run any target that
# depends on .env, and your value is gone with no message. That is the same
# silent-overwrite failure the rest of this repo spends its time avoiding.
#
# Precedence, lowest to highest:
#   1. .env.template   the tracked defaults
#   2. existing .env   YOUR overrides, preserved
#   3. .env.ports      generated, always wins (the port block is not an opinion)
#
# Reports what changed rather than doing it quietly.
set -eu
cd "$(dirname "$0")/.."
T=.env.template; E=.env; P=.env.ports
[ -f "$T" ] || { echo "no $T"; exit 1; }

./change/ports.sh alloc >/dev/null
[ -f "$P" ] || { echo "no $P after alloc"; exit 1; }

keys()  { grep -vE '^\s*(#|$)' "$1" 2>/dev/null | sed 's/=.*//' | sort -u; }
val()   { grep -E "^$2=" "$1" 2>/dev/null | tail -1 | cut -d= -f2-; }

tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by change/env.sh -- do not commit."
  echo "# Template defaults, then YOUR overrides, then the generated port block."
  sed -n '1,/^$/p' "$T" | grep -E '^\s*#' || true
} > "$tmp"

added=''; kept=''; orphan=''
for k in $(keys "$T"); do
  tv=$(val "$T" "$k")
  if [ -f "$E" ] && ev=$(val "$E" "$k") && [ -n "$ev" ] && [ "$ev" != "$tv" ]; then
    printf '%s=%s\n' "$k" "$ev" >> "$tmp"; kept="$kept $k"
  else
    printf '%s=%s\n' "$k" "$tv" >> "$tmp"
    [ -f "$E" ] && grep -qE "^$k=" "$E" 2>/dev/null || added="$added $k"
  fi
done

# Keys in .env but not in the template: keep them, but say so. Silently
# dropping a value someone set is what this script exists to prevent, and
# silently keeping an obsolete one is how config rots.
#
# Exclude the generated port keys: they came from .env.ports on the LAST run,
# so treating them as orphans copied them here and then appended them again --
# BASE_PORT twice, and a sourcing shell taking whichever came last.
if [ -f "$E" ]; then
  for k in $(keys "$E"); do
    grep -qE "^$k=" "$T" && continue
    grep -qE "^$k=" "$P" && continue
    printf '%s=%s\n' "$k" "$(val "$E" "$k")" >> "$tmp"; orphan="$orphan $k"
  done
fi

echo "" >> "$tmp"; echo "# --- generated port block ---" >> "$tmp"
cat "$P" >> "$tmp"
mv "$tmp" "$E"; trap - EXIT

echo "  .env composed"
[ -n "$added"  ] && echo "    new from template:$added"  || true
[ -n "$kept"   ] && echo "    your overrides kept:$kept" || true
[ -n "$orphan" ] && echo "    not in template (kept, but check):$orphan" || true
exit 0
